---
# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"

dotfiles_repo: https://github.com/kisamoto/dotfiles.git
dotfiles_repo_local_destination: ~/Development/github.com/kisamoto/dotfiles
dotfiles_files:
  - .aliases
  - .ansible.cfg
  - .bash_profile
  - .dash
  - .gitignore
  - .inputrc
  - .macos
  - .vim
  - .vimrc
  - .spacemacs
  - .taskrc
  - .tmux.conf
  - .zshrc

homebrew_installed_packages:
  - autoconf
  - awscli
  # - azure-cli
  - bash-completion
  - cookiecutter
  - cowsay
  - diff-so-fancy
  - dos2unix
  - emacs
  - exiftool
  - fd # alternative to find: https://github.com/sharkdp/fd
  - ffmpeg
  - fortune
  - gcc
  - git
  - glide
  - go
  - gpg
  - hammerspoon # Needed for the shiftit spoon https://github.com/peterklijn/hammerspoon-shiftit
  - htop
  - doxygen
  - gettext
  - git
  - github/gh/gh
  - gif-lfs
  - go
  - gpg
  - httpie
  - hugo
  - imagemagick
  # - jsonnet # JSON templating
  - jq
  - kotlin
  # - kubecfg # app from Bitnami for working with jsonnet on k8s
  - kubectx # easily switch between k8s clusters and namespaces
  - libevent
  - mosh
  - nmap
  - node
  # - openshift-cli
  # - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pipenv
  - pwgen
  - python3
  - readline
  - reattach-to-user-namespace # for tmux
  - ripgrep # fast search, replace `pt`
  - ruby # overrite the default installation
  - rust
  # - source-to-image
  - speedtest-cli
  - sqlite
  - ssh-copy-id
  - stormssh
  - stripe/stripe-cli/stripe
  - task
  - terraform
  - terragrunt
  - tmux
  - trash
  - tree
  - watch
  - wget
  - wrk
  - yarn
  - youtube-dl
  - z
  - zsh

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - java # at the top for android dependency
  - chromedriver
  - dash
  - discord
  - firefox
  - flux
  - google-chrome
  - handbrake
  - iina
  - iterm2
  - keepassxc
  - keepingyouawake
  - licecap
  - mactex
  - macvim
  - mattermost
  - onedrive
  - pycharm
  - skype
  - slack
  - spotify
  - sublime-text
  - the-unarchiver
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  # - android-sdk
  # - dropbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1171820258, name: "Highland 2 (2.9.9)" }
  - { id: 1255311569, name: "Time Zone Converter and Clock (1.7.5)" }
  - { id: 1274495053, name: "Microsoft To Do (2.45)" }
  - { id: 1295203466, name: "Microsoft Remote Desktop (10.6.6)" }
  - { id: 1352778147, name: "Bitwarden (1.26.5)" }
  - { id: 1451685025, name: "WireGuard (1.0.12)" }
  - { id: 408981434, name: "iMovie (10.2.3)" }
  - { id: 452695239, name: "QREncoder (1.5)" }
  - { id: 682658836, name: "GarageBand (10.4.3)" }
  - { id: 734418810, name: "SSH Tunnel (18.11.1)" }
  - { id: 824171161, name: "Affinity Designer (1.9.3)" }
  - { id: 824183456, name: "Affinity Photo (1.9.3)" }
  - { id: 912423770, name: "Command & Conquer Generals Deluxe Edition (1.1.2)" }
  - { id: 931134707, name: "Wire (3.25.4095)" }

# Create some useful directory structures
required_directories:
  - "~/.venvs"
  - "~/.ansible/roles"
  - "~/Development"
  - "~/go/bin"
  - "~/go/pkg"
  - "~/go/src"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
